title: Design Club
email: clubhouse@designclub.io
description: > # this means to ignore newlines until "baseurl:"
Where the creative community figure out what's next.
Every other month Design Club brings together designers 
of all disciplines and experience for drinks, good times, 
and original talks from leaders in our field. Speakers share 
their work, careers, and distinct perspectives on the industry.
baseurl: /design-club-site # the subpath of your site, e.g. /blog
url: "http://designclub.io" # the base hostname & protocol for your site
twitter_username: _DesignClub
github_username:  anothertompetty

# Build settings
markdown: kramdown

